'use client'
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import { createContext } from "react";
import useSecurity, { ConnectedUser, SecurityData } from "@/hooks/useSecurity.hook";

const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export const SecurityContext = createContext<SecurityData>({ connectedUser: undefined, login: () => Promise.resolve(), logout: () => {}});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const security = useSecurity();
  return (
    <html lang="en">
      <body className={inter.className}>
        <SecurityContext.Provider value={security}>
          <div>
            <Link href="/users">Users</Link>
            <Link href="/polls">Polls</Link>
            <Link href="/login">Login</Link>
            {security.connectedUser ? <span>Hello {security.connectedUser.name}</span> : <span>non connecté</span>}
          </div>
          {children}
        </SecurityContext.Provider>
      </body>
    </html>
  );
}
